### ISSUE TITLE
Crash with mesa-git and wayland

### ISSUE THREAD

**Issue by TheJackiMonster** [Songtronix/Airshipper#112]
When I run airshipper on Arch Linux with mesa-git installed I get a crash with following output:

```
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
[WARN] Missing features: SAMPLER_ANISOTROPY 
[WARN] Shader validation is disabled 
error marshalling arguments for create_prime_buffer: dup failed: Bad file descriptor
Error marshalling request: Bad file descriptor
[ERROR] Airshipper panicked: 

called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Other, message: "Bad file descriptor" }: panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Other, message: "Bad file descriptor" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.5.1/src/worker/mod.rs:272:14
thread 'smithay-clipboard' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Other, message: "Bad file descriptor" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.5.1/src/worker/mod.rs:272:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] Airshipper panicked: 

Next frame: Outdated: panicked at 'Next frame: Outdated', /home/runner/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/62295f5/wgpu/src/window/compositor.rs:130:52
thread 'main' panicked at 'Next frame: Outdated', /home/runner/.cargo/git/checkouts/iced-9e73d2fbe1fce35a/62295f5/wgpu/src/window/compositor.rs:130:52
[ERROR] Airshipper panicked: 

called `Result::unwrap()` on an `Err` value: "SendError(..)": panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.5.1/src/lib.rs:85:57
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-clipboard-0.5.1/src/lib.rs:85:57
stack backtrace:
   0:     0x55690b20029a - <unknown>
   1:     0x55690ae215cc - <unknown>
   2:     0x55690b1ffa81 - <unknown>
   3:     0x55690b1ff485 - <unknown>
   4:     0x55690b1fec53 - <unknown>
   5:     0x55690ad87ea6 - <unknown>
   6:     0x55690b1fe800 - <unknown>
   7:     0x55690b21c778 - <unknown>
   8:     0x55690b21c6ec - <unknown>
   9:     0x55690b21c69d - <unknown>
  10:     0x55690ae1ed90 - <unknown>
  11:     0x55690ae25c32 - <unknown>
  12:     0x55690b1f7b3b - <unknown>
  13:     0x55690af0367b - <unknown>
  14:     0x55690ac953b5 - <unknown>
  15:     0x55690ac36943 - <unknown>
  16:     0x55690ac40042 - <unknown>
  17:     0x55690acf308d - <unknown>
  18:     0x55690acdb3a4 - <unknown>
  19:     0x55690acd7a0e - <unknown>
  20:     0x55690ac3eb76 - <unknown>
  21:     0x55690ad8583a - <unknown>
  22:     0x55690ad9d036 - <unknown>
  23:     0x55690ac81553 - <unknown>
  24:     0x55690ada1e75 - <unknown>
  25:     0x7ff1585ce152 - __libc_start_main
  26:     0x55690ac2002a - <unknown>
  27:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

Airshipper does not crash using an X session with mesa-git though. So this could is probably a Wayland related bug.

**Comment by Songtronix** [comment]
I do not use Wayland myself so it's going to be hard for me to find the cause and fix it. I can only recommend using the cli then :/

**Comment by rosehuds** [comment]
The cause of this is the wrong vulkan impl being selected - lavapipe is a software renderer and also doesn't seem to like working on wayland. It's happening on my machine but can be fixed by specifying `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json` to force it to use radv instead of lavapipe. I don't know why lavapipe is being selected at all, given all other vulkan apps on my system happily choose radv by default. I just ran an example from iced master and can confirm it selected radv on its own (and fwiw also doesn't work if i specify lavapipe) - maybe this can be fixed by just updating iced?

**Comment by TheJackiMonster** [comment]
@rosehuds  I have also some experience with Vulkan. If that's the issue then the application has to select the proper device to fix this. Generally you can specify exactly which physical device to use in the Vulkan API (depending on features, index, extensions or name). So this should be something to fix on application level.

**Comment by rosehuds** [comment]
@TheJackiMonster airshipper does not use vulkan directly, it uses iced (and iced-wgpu), which in turn interact with vulkan. The driver selection is handled by iced.
