### ISSUE TITLE
Airshipper error on launch

### ISSUE THREAD

**Issue by AngelOnFira** [Songtronix/Airshipper#122]
**Describe the bug**

I'm trying to boot Airshipper that was installed on pamac from the AUR, but I'm getting this error:

```
[WARN] Missing features: SAMPLER_ANISOTROPY 
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
[WARN] Shader validation is disabled 
[ERROR] Airshipper panicked: 

surface does not support the adapter's queue family: panicked at 'surface does not support the adapter's queue family', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
thread 'main' panicked at 'surface does not support the adapter's queue family', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[ERROR] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 82273792, effective: 30096044 }, size: 2147483648 }
[ERROR] Memory leak: SizeEntry(256) is still used
[ERROR] Memory leak: SizeEntry(2048) is still used
[ERROR] Memory leak: SizeEntry(16384) is still used
[ERROR] Memory leak: SizeEntry(131072) is still used
[ERROR] Memory leak: SizeEntry(32768) is still used
[ERROR] Memory leak: SizeEntry(262144) is still used
[ERROR] Memory leak: SizeEntry(65536) is still used
[ERROR] Memory leak: SizeEntry(524288) is still used
[ERROR] Memory leak: SizeEntry(1048576) is still used
[ERROR] Memory leak: SizeEntry(2097152) is still used
[ERROR] Memory leak: SizeEntry(4194304) is still used
[ERROR] Memory leak: SizeEntry(25600) is still used
[ERROR] Memory leak: SizeEntry(204800) is still used
[ERROR] Memory leak: SizeEntry(51200) is still used
[ERROR] Memory leak: SizeEntry(409600) is still used
[ERROR] Memory leak: SizeEntry(102400) is still used
[ERROR] Memory leak: SizeEntry(819200) is still used
[ERROR] Memory leak: SizeEntry(1638400) is still used
[ERROR] Memory leak: SizeEntry(2600192) is still used
[ERROR] Memory leak: SizeEntry(5600000) is still used
[ERROR] Memory leak: SizeEntry(1400000) is still used
[ERROR] Memory leak: SizeEntry(12800) is still used
[ERROR] Memory leak: SizeEntry(240128) is still used
[ERROR] Memory leak: SizeEntry(40192) is still used
[ERROR] Memory leak: SizeEntry(321536) is still used
[ERROR] Memory leak: SizeEntry(80384) is still used
[ERROR] Memory leak: SizeEntry(643072) is still used
[ERROR] Memory leak: SizeEntry(160768) is still used
[ERROR] Memory leak: SizeEntry(1286144) is still used
[ERROR] Memory leak: SizeEntry(36096) is still used
[ERROR] Memory leak: SizeEntry(288768) is still used
[ERROR] Memory leak: SizeEntry(72192) is still used
[ERROR] Memory leak: SizeEntry(577536) is still used
[ERROR] Memory leak: SizeEntry(144384) is still used
[ERROR] Memory leak: SizeEntry(1155072) is still used
[ERROR] Memory leak: SizeEntry(16777216) is still used
[ERROR] Not all allocations from LinearAllocator were freed
[ERROR] DescriptorAllocator is dropped
```

This could be because of some underlying graphical issue on my system, but I was wondering if there was anything else I could debug.

**Desktop:**
 - OS: Garuda Linux
 - GPU: GTX 1070TI

**Comment by garpu** [comment]
Getting the same error, Nvidia geforce 1050ti, Slackware-current, 64-bit (with multilib), Nvidia driver: 460.56, rust 1.50.0.  Happens with 0.42, 0.41. 0.40 is fine.

**Comment by garpu** [comment]
Got a fix from the gamingonlinux discord:  VK_ICD_FILENAMES=/etc/vulkan/icd.d/nvidia_icd.json (or whatever and wherever the correct file is for your video card.) Airshipper starts right up.
