### ISSUE TITLE
Windows Client panics 

### ISSUE THREAD

**Issue by joedborg** [Songtronix/Airshipper#143]
**Describe the bug**
airshipper.exe crashes with the following:

```
[ERROR] Airshipper panicked:

connection to device was lost during initialization: panicked at 'connection to device was lost during initialization', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323:35
thread 'main' panicked at 'connection to device was lost during initialization', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323:35
stack backtrace:
   0:     0x7ff647c4860e - <unknown>
   1:     0x7ff6477c64cb - <unknown>
   2:     0x7ff647c473c8 - <unknown>
   3:     0x7ff647c469dc - <unknown>
   4:     0x7ff647c45d50 - <unknown>
   5:     0x7ff6477015dd - <unknown>
   6:     0x7ff647c45872 - <unknown>
   7:     0x7ff647c4edd5 - <unknown>
   8:     0x7ff647c4ed2f - <unknown>
   9:     0x7ff647c4eccf - <unknown>
  10:     0x7ff647c4ec90 - <unknown>
  11:     0x7ff647d00196 - <unknown>
  12:     0x7ff647ce8a3f - <unknown>
  13:     0x7ff647533dee - <unknown>
  14:     0x7ff6476fc848 - <unknown>
  15:     0x7ff647726561 - <unknown>
  16:     0x7ff647579466 - <unknown>
  17:     0x7ff647734d17 - <unknown>
  18:     0x7ff64801aae0 - <unknown>
  19:     0x7ff8c8d27034 - BaseThreadInitThunk
  20:     0x7ff8c9422651 - RtlUserThreadStart
```

This is from the Veloren downloads page (https://veloren.net/download/).  Let me know if I should be logging this there.

**To Reproduce**
try to run `airshipper.exe`

**Expected behavior**
airshipper opens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19042 Build 19042
 - GPU: Intel UHD and Nvidia GeForce GTX 1650 Ti

**Comment by Songtronix** [comment]
https://github.com/Songtronix/Airshipper/blob/staging/TROUBLESHOOTING.md
