### ISSUE TITLE
Crashes when minimized (on windows)

### ISSUE THREAD

**Issue by mhnghfv** [Songtronix/Airshipper#145]
**Describe the bug**
Crashes when minimized on windows

**To Reproduce**
1. Open launcher
2. Minimize

**Console output**
```
[WARN] Shader validation is disabled
[ERROR] Airshipper panicked:

not enough memory left: panicked at 'not enough memory left', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323:35
thread 'main' panicked at 'not enough memory left', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.6.0\src\backend\direct.rs:1323:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 90138112, effective: 35533312 }, size: 8657676288 }
[ERROR] Memory leak: SizeEntry(10240) is still used
[ERROR] Memory leak: SizeEntry(81920) is still used
[ERROR] Memory leak: SizeEntry(20480) is still used
[ERROR] Memory leak: SizeEntry(163840) is still used
[ERROR] Memory leak: SizeEntry(40960) is still used
[ERROR] Memory leak: SizeEntry(327680) is still used
[ERROR] Memory leak: SizeEntry(655360) is still used
[ERROR] Memory leak: SizeEntry(1310720) is still used
[ERROR] Memory leak: SizeEntry(222464) is still used
[ERROR] Memory leak: SizeEntry(166912) is still used
[ERROR] Memory leak: SizeEntry(256) is still used
[ERROR] Memory leak: SizeEntry(2048) is still used
[ERROR] Memory leak: SizeEntry(16384) is still used
[ERROR] Memory leak: SizeEntry(131072) is still used
[ERROR] Memory leak: SizeEntry(32768) is still used
[ERROR] Memory leak: SizeEntry(262144) is still used
[ERROR] Memory leak: SizeEntry(65536) is still used
[ERROR] Memory leak: SizeEntry(524288) is still used
[ERROR] Memory leak: SizeEntry(1048576) is still used
[ERROR] Memory leak: SizeEntry(2097152) is still used
[ERROR] Memory leak: SizeEntry(4194304) is still used
[ERROR] Memory leak: SizeEntry(25600) is still used
[ERROR] Memory leak: SizeEntry(204800) is still used
[ERROR] Memory leak: SizeEntry(51200) is still used
[ERROR] Memory leak: SizeEntry(409600) is still used
[ERROR] Memory leak: SizeEntry(102400) is still used
[ERROR] Memory leak: SizeEntry(819200) is still used
[ERROR] Memory leak: SizeEntry(1638400) is still used
[ERROR] Memory leak: SizeEntry(2600192) is still used
[ERROR] Memory leak: SizeEntry(5600000) is still used
[ERROR] Memory leak: SizeEntry(1400000) is still used
[ERROR] Memory leak: SizeEntry(12800) is still used
[ERROR] Memory leak: SizeEntry(240128) is still used
[ERROR] Memory leak: SizeEntry(40192) is still used
[ERROR] Memory leak: SizeEntry(321536) is still used
[ERROR] Memory leak: SizeEntry(80384) is still used
[ERROR] Memory leak: SizeEntry(643072) is still used
[ERROR] Memory leak: SizeEntry(160768) is still used
[ERROR] Memory leak: SizeEntry(1286144) is still used
[ERROR] Memory leak: SizeEntry(36096) is still used
[ERROR] Memory leak: SizeEntry(288768) is still used
[ERROR] Memory leak: SizeEntry(72192) is still used
[ERROR] Memory leak: SizeEntry(577536) is still used
[ERROR] Memory leak: SizeEntry(144384) is still used
[ERROR] Memory leak: SizeEntry(1155072) is still used
[ERROR] Memory leak: SizeEntry(16777216) is still used
[ERROR] Memory leak: SizeEntry(749056) is still used
[ERROR] DescriptorAllocator is dropped
```

**Desktop:**
 - OS: Windows
 - GPU: GTX 1060, also has Intel integrated graphics

**Comment by Songtronix** [comment]
Does anything mentioned [here](https://github.com/Songtronix/Airshipper/blob/staging/TROUBLESHOOTING.md) help?

**Comment by mhnghfv** [comment]
> 
> 
> Does anything mentioned [here](https://github.com/Songtronix/Airshipper/blob/staging/TROUBLESHOOTING.md) help?

All the mentioned fixes are either to use the cli mode or are fixes linux. The cli works well, but it'd be nice if someone fixed this gui bug

**Comment by Songtronix** [comment]
Yeah sadly I do not that much control over the libraries I use for the gui. Airshipper 0.5 will do a significant version bump and I would suggest trying it again then. Until then the cli will serve the purpose perfectly. An desktop icon (compatibility mode) is a shortcut for that to quickly get up and running.
