### ISSUE TITLE
Started getting this error on pop os

### ISSUE THREAD

**Issue by CronyTips** [Songtronix/Airshipper#150]
**Describe the bug**
I just starrted getting this error when launching airshipper recently.

**To Reproduce**

Don't have any clear instructions

**Expected behavior**
To lauch airshipper

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop os 20.10
 - GPU: nvidia gtx 1650

**Additional context**

```
[WARN] Skipping memory type with unknown flags DEVICE_LOCAL | DEVICE_COHERENT_AMD | DEVICE_UNCACHED_AMD
[WARN] Skipping memory type with unknown flags HOST_VISIBLE | HOST_COHERENT | DEVICE_COHERENT_AMD | DEVICE_UNCACHED_AMD
[WARN] Skipping memory type with unknown flags DEVICE_LOCAL | HOST_VISIBLE | HOST_COHERENT | DEVICE_COHERENT_AMD | DEVICE_UNCACHED_AMD
[WARN] Skipping memory type with unknown flags HOST_VISIBLE | HOST_COHERENT | HOST_CACHED | DEVICE_COHERENT_AMD | DEVICE_UNCACHED_AMD
[WARN] Shader validation is disabled
[ERROR] Airshipper panicked:

surface does not support the adapter's queue family: panicked at 'surface does not support the adapter's queue family', /build/airshipper-Pi52Jl/airshipper-0.4.2/vendor/wgpu/src/backend/direct.rs:1323:35
thread 'main' panicked at 'surface does not support the adapter's queue family', /build/airshipper-Pi52Jl/airshipper-0.4.2/vendor/wgpu/src/backend/direct.rs:1323:35
stack backtrace:
   0:     0x55b829425013 - <unknown>
   1:     0x55b82902321f - <unknown>
   2:     0x55b82941bc04 - <unknown>
   3:     0x55b82943e3c0 - <unknown>
   4:     0x55b82943e11a - <unknown>
   5:     0x55b828f86dee - <unknown>
   6:     0x55b82943e9b5 - <unknown>
   7:     0x55b829425438 - <unknown>
   8:     0x55b829425404 - <unknown>
   9:     0x55b82943d0cd - <unknown>
  10:     0x55b82943d090 - <unknown>
  11:     0x55b82950697d - <unknown>
  12:     0x55b829505c43 - <unknown>
  13:     0x55b828e2357f - <unknown>
  14:     0x55b828e3c382 - <unknown>
  15:     0x55b828ee2c1a - <unknown>
  16:     0x55b828ed9be4 - <unknown>
  17:     0x55b828ed60de - <unknown>
  18:     0x55b828e3aea7 - <unknown>
  19:     0x55b828f846a5 - <unknown>
  20:     0x55b828f98a06 - <unknown>
  21:     0x55b828e7e0c3 - <unknown>
  22:     0x55b828f9da4c - <unknown>
  23:     0x7f3dc562fcb2 - __libc_start_main
  24:     0x55b828e1c0de - <unknown>
  25:                0x0 - <unknown>
[ERROR] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 16777216, effective: 208 }, size: 3221225472 }
[ERROR] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 65496576, effective: 30095872 }, size: 2147483648 }
[ERROR] Memory leak: SizeEntry(256) is still used
[ERROR] Memory leak: SizeEntry(2048) is still used
[ERROR] Memory leak: SizeEntry(16384) is still used
[ERROR] Memory leak: SizeEntry(131072) is still used
[ERROR] Memory leak: SizeEntry(32768) is still used
[ERROR] Memory leak: SizeEntry(262144) is still used
[ERROR] Memory leak: SizeEntry(65536) is still used
[ERROR] Memory leak: SizeEntry(524288) is still used
[ERROR] Memory leak: SizeEntry(1048576) is still used
[ERROR] Memory leak: SizeEntry(2097152) is still used
[ERROR] Memory leak: SizeEntry(4194304) is still used
[ERROR] Memory leak: SizeEntry(25600) is still used
[ERROR] Memory leak: SizeEntry(204800) is still used
[ERROR] Memory leak: SizeEntry(51200) is still used
[ERROR] Memory leak: SizeEntry(409600) is still used
[ERROR] Memory leak: SizeEntry(102400) is still used
[ERROR] Memory leak: SizeEntry(819200) is still used
[ERROR] Memory leak: SizeEntry(1638400) is still used
[ERROR] Memory leak: SizeEntry(2600192) is still used
[ERROR] Memory leak: SizeEntry(5600000) is still used
[ERROR] Memory leak: SizeEntry(1400000) is still used
[ERROR] Memory leak: SizeEntry(12800) is still used
[ERROR] Memory leak: SizeEntry(240128) is still used
[ERROR] Memory leak: SizeEntry(40192) is still used
[ERROR] Memory leak: SizeEntry(321536) is still used
[ERROR] Memory leak: SizeEntry(80384) is still used
[ERROR] Memory leak: SizeEntry(643072) is still used
[ERROR] Memory leak: SizeEntry(160768) is still used
[ERROR] Memory leak: SizeEntry(1286144) is still used
[ERROR] Memory leak: SizeEntry(36096) is still used
[ERROR] Memory leak: SizeEntry(288768) is still used
[ERROR] Memory leak: SizeEntry(72192) is still used
[ERROR] Memory leak: SizeEntry(577536) is still used
[ERROR] Memory leak: SizeEntry(144384) is still used
[ERROR] Memory leak: SizeEntry(1155072) is still used
[ERROR] Memory leak: SizeEntry(16777216) is still used
[ERROR] Not all allocations from LinearAllocator were freed
[ERROR] DescriptorAllocator is dropped
```

**Comment by Th3Dilli** [comment]
Got a similar bug.

I am using Ubuntu 21.04
GNOME 3.38.5 -- X11
NVIDIA RTX 2080 TI -- Driver 460.80

`
dilli@dilli-pc:~/Downloads/airshipper-linux$ ./airshipper 
[WARN] Missing features: SAMPLER_ANISOTROPY 
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
[WARN] Shader validation is disabled 
[ERROR] Airshipper panicked: 

surface does not support the adapter's queue family: panicked at 'surface does not support the adapter's queue family', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
thread 'main' panicked at 'surface does not support the adapter's queue family', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 82273792, effective: 30096044 }, size: 2147483648 }
[ERROR] Memory leak: SizeEntry(256) is still used
[ERROR] Memory leak: SizeEntry(2048) is still used
[ERROR] Memory leak: SizeEntry(16384) is still used
[ERROR] Memory leak: SizeEntry(131072) is still used
[ERROR] Memory leak: SizeEntry(32768) is still used
[ERROR] Memory leak: SizeEntry(262144) is still used
[ERROR] Memory leak: SizeEntry(65536) is still used
[ERROR] Memory leak: SizeEntry(524288) is still used
[ERROR] Memory leak: SizeEntry(1048576) is still used
[ERROR] Memory leak: SizeEntry(2097152) is still used
[ERROR] Memory leak: SizeEntry(4194304) is still used
[ERROR] Memory leak: SizeEntry(25600) is still used
[ERROR] Memory leak: SizeEntry(204800) is still used
[ERROR] Memory leak: SizeEntry(51200) is still used
[ERROR] Memory leak: SizeEntry(409600) is still used
[ERROR] Memory leak: SizeEntry(102400) is still used
[ERROR] Memory leak: SizeEntry(819200) is still used
[ERROR] Memory leak: SizeEntry(1638400) is still used
[ERROR] Memory leak: SizeEntry(2600192) is still used
[ERROR] Memory leak: SizeEntry(5600000) is still used
[ERROR] Memory leak: SizeEntry(1400000) is still used
[ERROR] Memory leak: SizeEntry(12800) is still used
[ERROR] Memory leak: SizeEntry(240128) is still used
[ERROR] Memory leak: SizeEntry(40192) is still used
[ERROR] Memory leak: SizeEntry(321536) is still used
[ERROR] Memory leak: SizeEntry(80384) is still used
[ERROR] Memory leak: SizeEntry(643072) is still used
[ERROR] Memory leak: SizeEntry(160768) is still used
[ERROR] Memory leak: SizeEntry(1286144) is still used
[ERROR] Memory leak: SizeEntry(36096) is still used
[ERROR] Memory leak: SizeEntry(288768) is still used
[ERROR] Memory leak: SizeEntry(72192) is still used
[ERROR] Memory leak: SizeEntry(577536) is still used
[ERROR] Memory leak: SizeEntry(144384) is still used
[ERROR] Memory leak: SizeEntry(1155072) is still used
[ERROR] Memory leak: SizeEntry(16777216) is still used
[ERROR] Not all allocations from LinearAllocator were freed
[ERROR] DescriptorAllocator is dropped
`

i also tried compiling it with rust (cargo run --release) but same issue.

but cargo run results this (first line differs)

`
[WARN] Unable to find layer: VK_LAYER_KHRONOS_validation
[WARN] Missing features: SAMPLER_ANISOTROPY 
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
[WARN] Shader validation is disabled 
[ERROR] Airshipper panicked: 

surface does not support the adapter's queue family: panicked at 'surface does not support the adapter's queue family', /home/dilli/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
thread 'main' panicked at 'surface does not support the adapter's queue family', /home/dilli/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR] Heaps not completely freed before drop. Utilization: MemoryHeapUtilization { utilization: MemoryUtilization { used: 82273792, effective: 30096044 }, size: 2147483648 }
[ERROR] Memory leak: SizeEntry(256) is still used
[ERROR] Memory leak: SizeEntry(2048) is still used
[ERROR] Memory leak: SizeEntry(16384) is still used
[ERROR] Memory leak: SizeEntry(131072) is still used
[ERROR] Memory leak: SizeEntry(32768) is still used
[ERROR] Memory leak: SizeEntry(262144) is still used
[ERROR] Memory leak: SizeEntry(65536) is still used
[ERROR] Memory leak: SizeEntry(524288) is still used
[ERROR] Memory leak: SizeEntry(1048576) is still used
[ERROR] Memory leak: SizeEntry(2097152) is still used
[ERROR] Memory leak: SizeEntry(4194304) is still used
[ERROR] Memory leak: SizeEntry(25600) is still used
[ERROR] Memory leak: SizeEntry(204800) is still used
[ERROR] Memory leak: SizeEntry(51200) is still used
[ERROR] Memory leak: SizeEntry(409600) is still used
[ERROR] Memory leak: SizeEntry(102400) is still used
[ERROR] Memory leak: SizeEntry(819200) is still used
[ERROR] Memory leak: SizeEntry(1638400) is still used
[ERROR] Memory leak: SizeEntry(2600192) is still used
[ERROR] Memory leak: SizeEntry(5600000) is still used
[ERROR] Memory leak: SizeEntry(1400000) is still used
[ERROR] Memory leak: SizeEntry(12800) is still used
[ERROR] Memory leak: SizeEntry(240128) is still used
[ERROR] Memory leak: SizeEntry(40192) is still used
[ERROR] Memory leak: SizeEntry(321536) is still used
[ERROR] Memory leak: SizeEntry(80384) is still used
[ERROR] Memory leak: SizeEntry(643072) is still used
[ERROR] Memory leak: SizeEntry(160768) is still used
[ERROR] Memory leak: SizeEntry(1286144) is still used
[ERROR] Memory leak: SizeEntry(36096) is still used
[ERROR] Memory leak: SizeEntry(288768) is still used
[ERROR] Memory leak: SizeEntry(72192) is still used
[ERROR] Memory leak: SizeEntry(577536) is still used
[ERROR] Memory leak: SizeEntry(144384) is still used
[ERROR] Memory leak: SizeEntry(1155072) is still used
[ERROR] Memory leak: SizeEntry(16777216) is still used
[ERROR] Not all allocations from LinearAllocator were freed
[ERROR] DescriptorAllocator is dropped
`

hope this may help, let me know if i should try something else.

**Comment by Th3Dilli** [comment]
As mentioned in #122 i managed to get it working with 
`export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` for Ubuntu 21.04
