### ISSUE TITLE
[Feature] Version Select

### ISSUE THREAD

**Issue by MohammadWaleed** [Songtronix/Airshipper#61]
I just downloaded Airshipper and got the latest updates and the game is not starting understandably,
So what about giving the option to choose between versions ?
if the nightly build is broken i can go back to the latest "stable" release

**Comment by Songtronix** [comment]
The current nightly is working just fine for me. Could you clarify what error is occuring for you?
Supporting stable and nightly version of Veloren is a planned feature :ok_hand:

**Comment by MohammadWaleed** [comment]
Awesome,

i just tried again the same thing happened,

```
thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `false`,
    right: `true`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.10.0/src/host/wasapi/device.rs:439:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.10.0/src/host/wasapi/device.rs:652:31

stack backtrace:
0:           0x938e59 - backtrace::backtrace::dbghelp::trace::hc960947381f8dab1     at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\dbghelp.rs:88
1:           0x938e59 - backtrace::backtrace::trace_unsynchronized::he76498ab00bd3e3e   at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
2:           0x938e59 - std::sys_common::backtrace::_print_fmt::h919c6a8e6d60ff71   at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\sys_common\backtrace.rs:78
3:           0x938e59 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha54c270d918a31e1    at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\sys_common\backtrace.rs:59
4:           0x483b4b - core::fmt::write::h5b5fa7d461070d53 at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libcore\fmt\mod.rs:1053
5:           0x938167 - std::io::Write::write_fmt::h68e1a9bd3128acbe    at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\io\mod.rs:1428
6:           0x937dfe - std::sys_common::backtrace::_print::h0096f4d5e85a2486   at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\sys_common\backtrace.rs:62
7:           0x937dfe - std::sys_common::backtrace::print::haa66b94210f51cea    at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\sys_common\backtrace.rs:49
8:           0x937dfe - std::panicking::default_hook::{{closure}}::hda6758c436864c9c    at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\panicking.rs:204
9:           0x93711f - std::panicking::default_hook::hd8bd09d68d4cbca3 at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\panicking.rs:224
10:           0x936b74 - std::panicking::rust_panic_with_hook::h1344b4d87a87ed45    at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\panicking.rs:470
11:           0x93c78b - rust_begin_unwind  at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libstd\panicking.rs:378
12:           0x481460 - core::panicking::panic_fmt::hb01fc807ff2e7487  at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libcore\panicking.rs:85
13:           0x487f53 - core::option::expect_none_failed::he6ee473162b5191d    at /rustc/75cf41afb468152611212271bae026948cd3ba46\/src\libcore\option.rs:1211
14:           0xe37c5c - core::ptr::drop_in_place::hf142e709f7b127db
15:           0xe4a936 - veloren_voxygen::audio::get_device_raw::hac3855bbd629a514
16:           0x407fa4 - veloren_voxygen::main::h976ce0c0148737a8
17:           0xbaf306 - std::rt::lang_start::{{closure}}::h2fda1d326507ea7a
18:           0x40cfd6 - main
19:           0x4013c7 - __tmainCRTStartup  at ./mingw-w64-crt/crt/crtexe.c:339
20:           0x4014fb - mainCRTStartup at ./mingw-w64-crt/crt/crtexe.c:223
21:           0x7ffd667e7bd4 - _report_error
22:           0x7ffd669eced1 - _report_error

thread panicked while panicking. aborting.     
```

i tried again while writing this response and it worked, this is weird...

**Comment by Songtronix** [comment]
Based on that error it might be audio related. Did you plug something in/out?
I would recommend to head over to our discord and [report](https://discord.gg/BZXKHxX) it there maybe someone knows more about that issue ^^

**Comment by MohammadWaleed** [comment]
I guess i had my headphones plugged in, i tried to reproduce the issue and couldn't either way i'll report it, thank you
